Feature/splashscreen
jurczewski/PandeMania pull request #11
Opened 2021-02-15 19:03 UTC by shreq

2021-02-15 19:21 UTC, jurczewski approved these changes
LGTM

2021-02-18 10:12 UTC, Pawci0 requested changes

2021-02-18 10:12 UTC, Pawci0 commented on pandemania/src/FirebaseConfig.js
> +const config = {
firebase config file will be added with the firebase feature, please remove it from this commit

2021-02-19 11:24 UTC, Pawci0 approved these changes

2021-02-19 11:24 UTC, merged