Minimalist UI table
jurczewski/PandeMania pull request #14
Opened 2021-02-18 23:27 UTC by jurczewski

2021-02-18 23:33 UTC, shreq approved these changes

2021-02-19 11:36 UTC, Pawci0 requested changes
[should]
When you choose a country with no data, the table does not clear and shows data of previously chosen country. Please fix it

2021-02-19 11:36 UTC, Pawci0 commented on pandemania/src/components/Layout/Layout.jsx
> +				<TableWrapper countryName={pickedCountry.slug} />
[could]
i think the table would look better with a bottom margin

2021-02-20 15:08 UTC, Pawci0 approved these changes

2021-02-20 15:09 UTC, merged